### PR TITLE
Fix bottom nav on page change

### LINKED ISSUE #113: fix bottom nav when transitioning to MyGarden page

### PR DESCRIPTION
**Pull request by conalli**
## Description

Add global state for current page to help bottom nav update correctly

## Closes issue(s)

Closes #113 

## Screenshots

If you have image share...

## Changes include

- [x] Bugfix (non-breaking change that solves an issue)

## Checklist

- [x] I have tested this code

### CODE REVIEW

File: src/pages/CreateGarden/index.tsx [hunk 1]
```diff
@@ -171,6 +173,7 @@ export const CreateGarden = () => {
         gardenId,
       }));
       await createNewGardenRules(rules);
+      setCurrentPage(`/user/dailyGardening/${gardenId}`);
```
Comment (conalli) [inline src/pages/CreateGarden/index.tsx:176]: Update current page state whenever we go to new page

**Review by kome12 — APPROVED** [review]
LGTM!

**Review by daiHash — APPROVED** [review]

**Review by curtisahuang — APPROVED** [review]
Lgtm!
