### PR TITLE
Fix scroll for mobile in My Growth

### LINKED ISSUE #219: Side scrolls on My Growth page when there are many tabs
https://user-images.githubusercontent.com/770480/133786532-aadb9758-0b54-4649-b18f-419882b8d790.mov

### PR DESCRIPTION
**Pull request by kome12**
## Description

Fix side scroll when tabs length increases

## Closes issue(s)

Closes #219 

## Screenshots

https://user-images.githubusercontent.com/770480/133791186-0b1be16e-c1c0-43c8-a406-9eddccf8eae6.mov

## Changes include

- [X] Bugfix (non-breaking change that solves an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

## Checklist

- [X] I have tested this code
- [ ] Add here the checks for this PR. If any please delete these checks

### CODE REVIEW

File: src/pages/MyGrowth/index.tsx [hunk 1]
```diff
@@ -1,25 +1,26 @@
...
+import { useApi } from "../../utils/api/useApi";
+import { TabData } from "./components/TabData";
+import { TabPanel } from "./components/TabPanel";
 
 const useStyles = makeStyles((theme: Theme) =>
   createStyles({
     tabBar: {
       backgroundColor: theme.palette.primary.main,
       // display: "flex",
       // flex: "0 0 100%",
```
Comment (daiHash) [inline src/pages/MyGrowth/index.tsx:20]: Please remove this code if not needed

**Review by daiHash — APPROVED** [review]
LGTM👍

File: src/pages/MyGrowth/index.tsx (hunk 1 above)
Comment (kome12) [reply src/pages/MyGrowth/index.tsx]: Removed!
